name: Deploy Rspress site to Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create redirect index.html
        run: |
          mkdir public
          echo '<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="0; url=https://yourdomain.com/repo/">
    <script>
      const basePath = "/repo";
      const target = "https://yourdomain.com";
      const path = location.pathname.replace(basePath, "");
      const search = location.search;
      const hash = location.hash;
      location.href = `${target}${path}${search}${hash}`;
    </script>
    <title>Redirecting...</title>
  </head>
  <body>
    <p>Redirecting...</p>
  </body>
</html>' > public/index.html
          touch public/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public