# .github/workflows/release.yml

name: Release & Publish

on:
  push:
    tags:
      - 'v*' # ex: v1.2.3

permissions:
  contents: write

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - run: pnpm install

      - name: Extract version from tag
        id: version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$TAG_VERSION" >> "$GITHUB_OUTPUT"

      - name: Run release with Nx
        run: |
          pnpm clear
          pnpm build
          pnpm nx release --specifier=${{ steps.version.outputs.version }} --skip-publish

      - name: Push updated files to main branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: release ${{ steps.version.outputs.version }}"
          git push origin main

      - name: Publish all packages
        run: pnpm publish:all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
